Repository fredmorcos/tvrank, pull requests merged in 2022-03, with the labels that each got.

#16 Gitpod Rust and mobbing development setup
  .gitpod.yml
Labels: enhancement

#15 #11 Make the TVrank command-line interface more convenient
  README.md
  src/main.rs
Labels: enhancement

#21 Dependency updates
  Cargo.lock
Labels: enhancement

#22 Add support to display only top n results
  src/main.rs
  src/search.rs
Labels: enhancement

#23 Small improvements
  src/main.rs
  src/search.rs
Labels: enhancement

#24 Fix download speed reporting and use a progress bar when possible
  examples/query.rs
  src/imdb/db.rs
  src/imdb/mod.rs
  src/imdb/progress.rs
  src/imdb/ratings.rs
  src/imdb/service.rs
  src/main.rs
  src/ui.rs
Labels: bug, enhancement

#34 print status output to stderr
  src/main.rs
Labels: enhancement

#37 Document the internal TVrank library
  src/imdb/db.rs
  src/imdb/error.rs
  src/imdb/genre.rs
  src/imdb/progress.rs
  src/imdb/ratings.rs
  src/imdb/service.rs
  src/imdb/title.rs
  src/imdb/title_header.rs
  src/imdb/title_id.rs
  src/imdb/title_type.rs
  src/imdb/utils.rs
  src/lib.rs
Labels: documentation

#35 Support JSON output
  src/imdb/genre.rs
  src/imdb/ratings.rs
  src/imdb/title.rs
  src/imdb/title_header.rs
  src/imdb/title_id.rs
  src/imdb/title_type.rs
  src/main.rs
  src/print.rs
  src/search.rs
Labels: enhancement

#39 Support YAML output #18
  Cargo.lock
  Cargo.toml
  README.md
  src/main.rs
  src/print.rs
Labels: enhancement

#40 Fix GitPod toolchain setup
  .gitpod.yml
Labels: meta

#43 Cleanups and rework of option parsing
  .vscode/settings.json
  src/main.rs
  src/print.rs
Labels: enhancement
