Repository fredmorcos/tvrank, pull requests merged in 2022-04, with the labels that each got.

#50 Fix search results when keywords contain "the" as part of another word
  src/imdb/db.rs
  src/imdb/service.rs
  src/main.rs
Labels: bug, enhancement

#53 Implement the `mark` subcommand
  README.md
  src/imdb/title_id.rs
  src/info.rs
  src/main.rs
Labels: enhancement

#48 Split workflows into jobs to speed up CI
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: meta

#57 Cache dependencies between Cargo runs
  .github/workflows/build-test-publish.yml
Labels: meta

#58 Refactor parts of Service and Db into ServiceDb
  lib/src/imdb/db.rs
  lib/src/imdb/service.rs
Labels: refactoring
